"""General, model-independent discrete geometries."""

from toposc_lab.geometry.base import Geometry, GeometryEdge
from toposc_lab.geometry.generators import (
    BODY_CENTERED_CUBIC_GENERATOR,
    BUILTIN_GEOMETRY_GENERATORS,
    CHAIN_GENERATOR,
    CUBIC_GENERATOR,
    HONEYCOMB_GENERATOR,
    IRREGULAR_CLUSTER_GENERATOR,
    KAGOME_GENERATOR,
    RING_GENERATOR,
    SQUARE_GENERATOR,
    TRIANGULAR_GENERATOR,
    FunctionGeometryGenerator,
    GeometryGenerationRequest,
    GeometryGenerator,
    GeometryGeneratorRegistry,
    body_centered_cubic,
    chain,
    cubic,
    honeycomb,
    irregular_cluster,
    kagome,
    ring,
    square,
    triangular,
)

__all__ = [
    "BODY_CENTERED_CUBIC_GENERATOR",
    "BUILTIN_GEOMETRY_GENERATORS",
    "CHAIN_GENERATOR",
    "CUBIC_GENERATOR",
    "FunctionGeometryGenerator",
    "Geometry",
    "GeometryEdge",
    "GeometryGenerationRequest",
    "GeometryGenerator",
    "GeometryGeneratorRegistry",
    "HONEYCOMB_GENERATOR",
    "IRREGULAR_CLUSTER_GENERATOR",
    "KAGOME_GENERATOR",
    "RING_GENERATOR",
    "SQUARE_GENERATOR",
    "TRIANGULAR_GENERATOR",
    "body_centered_cubic",
    "chain",
    "cubic",
    "honeycomb",
    "irregular_cluster",
    "kagome",
    "ring",
    "square",
    "triangular",
]
