"""Reproducible robustness-testing contracts."""

from toposc_lab.robustness.coordinate import (
    UNIFORM_COORDINATE_PERTURBATION_KEY,
    UNIFORM_COORDINATE_PERTURBATION_VERSION,
    apply_uniform_coordinate_perturbation,
)
from toposc_lab.robustness.disorder import (
    DISORDER_RNG_ALGORITHM,
    HAMILTONIAN_ID_SCHEME,
    MODEL_PARAMETER_SET_ID_SCHEME,
    DisorderParameterValue,
    DisorderProvenance,
    DisorderRealization,
    DisorderRequest,
    DisorderSnapshot,
    DisorderState,
    DisorderTarget,
    DisorderTransform,
    FunctionDisorderTransform,
    ModelParameterSet,
    exact_hamiltonian_id,
    exact_model_parameter_set_id,
    realize_disorder,
)
from toposc_lab.robustness.edge_removal import (
    RANDOM_EDGE_REMOVAL_KEY,
    RANDOM_EDGE_REMOVAL_VERSION,
    apply_random_edge_removal,
)
from toposc_lab.robustness.ensemble import (
    DISORDER_ENSEMBLE_EXECUTION_VERSION,
    DisorderEnsembleFailure,
    DisorderEnsembleFailureStage,
    DisorderEnsembleMember,
    DisorderEnsembleRequest,
    DisorderEnsembleResult,
    DisorderEvaluationFactory,
    DisorderOutcome,
    DisorderRealizationFactory,
    execute_disorder_ensemble,
)
from toposc_lab.robustness.finite_size import (
    FINITE_SIZE_SCALING_VERSION,
    FiniteSizeRobustnessPoint,
    FiniteSizeScalingMethod,
    FiniteSizeScalingResult,
    FiniteSizeScalingSpec,
    fit_finite_size_scaling,
)
from toposc_lab.robustness.family import (
    GEOMETRY_FAMILY_CONTRACT_VERSION,
    CrossSizeGeometryFamily,
    GeometryFamilyMember,
    GeometryFamilySeedPolicy,
    GeometryFamilySpec,
    create_cross_size_geometry_family,
)
from toposc_lab.robustness.hopping import (
    UNIFORM_HOPPING_DISORDER_KEY,
    UNIFORM_HOPPING_DISORDER_VERSION,
    apply_uniform_hopping_disorder,
)
from toposc_lab.robustness.metrics import (
    RobustnessFractionMetric,
    RobustnessSuccessCriterion,
    RobustnessSuccessPredicate,
    compute_robustness_fraction,
)
from toposc_lab.robustness.node_removal import (
    RANDOM_NODE_REMOVAL_KEY,
    RANDOM_NODE_REMOVAL_VERSION,
    NodeRemovalRealization,
    apply_random_node_removal,
)
from toposc_lab.robustness.onsite import (
    UNIFORM_ONSITE_DISORDER_KEY,
    UNIFORM_ONSITE_DISORDER_VERSION,
    apply_uniform_onsite_disorder,
)
from toposc_lab.robustness.pairing import (
    UNIFORM_PAIRING_DISORDER_KEY,
    UNIFORM_PAIRING_DISORDER_VERSION,
    PairingDisorderChannel,
    apply_uniform_pairing_disorder,
)
from toposc_lab.robustness.parameters import (
    UNIFORM_PARAMETER_PERTURBATION_KEY,
    UNIFORM_PARAMETER_PERTURBATION_VERSION,
    apply_uniform_parameter_perturbation,
)
from toposc_lab.robustness.report import (
    ROBUSTNESS_REPORT_VERSION,
    RobustnessReport,
    RobustnessReportEntry,
    create_robustness_report,
)
from toposc_lab.robustness.uncertainty import (
    ROBUSTNESS_UNCERTAINTY_VERSION,
    RobustnessUncertaintyEstimate,
    RobustnessUncertaintyMethod,
    estimate_robustness_uncertainty,
)

__all__ = [
    "DISORDER_RNG_ALGORITHM",
    "DISORDER_ENSEMBLE_EXECUTION_VERSION",
    "FINITE_SIZE_SCALING_VERSION",
    "GEOMETRY_FAMILY_CONTRACT_VERSION",
    "HAMILTONIAN_ID_SCHEME",
    "MODEL_PARAMETER_SET_ID_SCHEME",
    "RANDOM_EDGE_REMOVAL_KEY",
    "RANDOM_EDGE_REMOVAL_VERSION",
    "RANDOM_NODE_REMOVAL_KEY",
    "RANDOM_NODE_REMOVAL_VERSION",
    "ROBUSTNESS_UNCERTAINTY_VERSION",
    "ROBUSTNESS_REPORT_VERSION",
    "UNIFORM_COORDINATE_PERTURBATION_KEY",
    "UNIFORM_COORDINATE_PERTURBATION_VERSION",
    "UNIFORM_HOPPING_DISORDER_KEY",
    "UNIFORM_HOPPING_DISORDER_VERSION",
    "UNIFORM_ONSITE_DISORDER_KEY",
    "UNIFORM_ONSITE_DISORDER_VERSION",
    "UNIFORM_PAIRING_DISORDER_KEY",
    "UNIFORM_PAIRING_DISORDER_VERSION",
    "UNIFORM_PARAMETER_PERTURBATION_KEY",
    "UNIFORM_PARAMETER_PERTURBATION_VERSION",
    "DisorderParameterValue",
    "DisorderEnsembleFailure",
    "DisorderEnsembleFailureStage",
    "DisorderEnsembleMember",
    "DisorderEnsembleRequest",
    "DisorderEnsembleResult",
    "DisorderEvaluationFactory",
    "DisorderOutcome",
    "DisorderProvenance",
    "DisorderRealization",
    "DisorderRequest",
    "DisorderRealizationFactory",
    "DisorderSnapshot",
    "DisorderState",
    "DisorderTarget",
    "DisorderTransform",
    "CrossSizeGeometryFamily",
    "FiniteSizeRobustnessPoint",
    "FiniteSizeScalingMethod",
    "FiniteSizeScalingResult",
    "FiniteSizeScalingSpec",
    "FunctionDisorderTransform",
    "GeometryFamilyMember",
    "GeometryFamilySeedPolicy",
    "GeometryFamilySpec",
    "ModelParameterSet",
    "NodeRemovalRealization",
    "PairingDisorderChannel",
    "RobustnessFractionMetric",
    "RobustnessReport",
    "RobustnessReportEntry",
    "RobustnessSuccessCriterion",
    "RobustnessSuccessPredicate",
    "RobustnessUncertaintyEstimate",
    "RobustnessUncertaintyMethod",
    "apply_random_edge_removal",
    "apply_random_node_removal",
    "apply_uniform_coordinate_perturbation",
    "apply_uniform_hopping_disorder",
    "apply_uniform_onsite_disorder",
    "apply_uniform_pairing_disorder",
    "apply_uniform_parameter_perturbation",
    "compute_robustness_fraction",
    "create_cross_size_geometry_family",
    "create_robustness_report",
    "estimate_robustness_uncertainty",
    "exact_hamiltonian_id",
    "exact_model_parameter_set_id",
    "execute_disorder_ensemble",
    "fit_finite_size_scaling",
    "realize_disorder",
]
